"""Initial


Revision ID: 0001
Revises:
Create Date: 2026-07-08 09:10:50.126375


"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author")),
        schema="project_template",
    )
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["project_template.author.id"],
            name=op.f("fk_book_author_id_author"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
        schema="project_template",
    )
    op.create_table(
        "chapter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["project_template.author.id"],
            name=op.f("fk_chapter_author_id_author"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["project_template.book.id"],
            name=op.f("fk_chapter_book_id_book"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapter")),
        schema="project_template",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chapter", schema="project_template")
    op.drop_table("book", schema="project_template")
    op.drop_table("author", schema="project_template")
    # ### end Alembic commands ###
