import datetime

from fastapi_filter.contrib.sqlalchemy import Filter
from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    Integer,
    Numeric,
    String,
    Text,
    inspect,
)


class BaseFilter(Filter):
    """
    Base class for filter classes. Attribute 'model' must be implemented per FilterClass.
    """

    class Constants(Filter.Constants):
        model = None


class BaseModelFilter(BaseFilter):
    """
    Base class for all model filter classes with autogenerated filters.
    Attribute 'model' must be implemented per FilterClass.


    Depends on the attribute type it generates proper fields for filtering. You can specify fields using:


    class Constants(Filter.Constants):
        fields = "__all__"  # or list of fields or string with list of fields with comma separated values
        exclude_fields = "a,b"  # or None or list of fields or string with list of fields with comma separated values


    You can also adjust _OPERATORS per filter.
    """

    class Constants(Filter.Constants):
        fields: str | list[str]
        exclude_fields: str | list[str] | None = None

    _STRING_OPERATORS = ["eq", "neq", "like", "ilike", "isnull"]
    _NUMBER_OPERATORS = ["eq", "neq", "gt", "gte", "lt", "lte", "in"]
    _DATETIME_OPERATORS = ["eq", "neq", "gt", "gte", "lt", "lte"]
    _BOOL_OPERATORS = ["eq", "isnull"]

    def __init_subclass__(cls, **kwargs):
        constants: BaseModelFilter.Constants | None = getattr(cls, "Constants", None)

        assert (
            constants and constants.model and constants.fields
        ), "To use ModelFilter please implement Constants.model and Constants.fields."
        annotations = dict(getattr(cls, "__annotations__", {}))
        selected, all_columns = cls._get_fields_metadata(constants)

        for field_name in selected:
            if field_name in annotations:
                # User explicitly defined it
                continue

            column = all_columns[field_name]
            column_type = column.type

            operators, py_type = cls._get_operators(column_type)
            if not operators:
                continue

            for op in operators.default:
                attr_name = field_name if op == "eq" else f"{field_name}__{op}"
                if attr_name not in annotations:
                    annotations[attr_name] = py_type | None
                    setattr(cls, attr_name, None)

        cls.__annotations__ = annotations
        super().__init_subclass__(**kwargs)

    @staticmethod
    def _get_fields_metadata(constants):
        fields = getattr(constants, "fields", "__all__")
        exclude = set(getattr(constants, "exclude_fields", []) or [])
        if isinstance(exclude, str):
            exclude = set(exclude.split(","))

        mapper = inspect(constants.model)
        all_columns = {column.key: column for column in mapper.columns}

        if fields == "__all__":
            selected = set(all_columns.keys())
        elif isinstance(fields, str):
            selected = set(fields.split(","))
        else:
            selected = set(fields)

        selected -= exclude
        return selected, all_columns

    @classmethod
    def _get_operators(cls, column_type):
        if isinstance(column_type, (String, Text)):
            operators = cls._STRING_OPERATORS
            py_type = str
        elif isinstance(column_type, (Integer, Float, Numeric)):
            operators = cls._NUMBER_OPERATORS
            py_type = int if isinstance(column_type, Integer) else float
        elif isinstance(column_type, (DateTime, Date)):
            operators = cls._DATETIME_OPERATORS
            py_type = (
                datetime.datetime
                if isinstance(column_type, DateTime)
                else datetime.date
            )
        elif isinstance(column_type, Boolean):
            operators = cls._BOOL_OPERATORS
            py_type = bool
        else:
            return None, None
        return operators, py_type
